spring:
  application:
    name: playlist
  data:
    redis:
      host: ${HOST_REDIS}
      port: 6379
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


server:
  port: 80

resilience4j.retry:
  instances:
    openWeatherMapRetry:
      maxAttempts: 5
      waitDuration: 1s
      exponentialBackoff:
        multiplier: 2
        maxDelay: 5s
      retryExceptions:
        - java.io.IOException
        - org.springframework.web.client.HttpClientErrorException
        - java.net.SocketException

#logging:
#  level:
#    root: DEBUG

