name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: HML

    steps:
      - name: Verify AWS CLI Installation
        run: aws --version

      - name: Checkout code
        uses: actions/checkout@v4

      # Setup do AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Login no Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 024848472141.dkr.ecr.us-east-2.amazonaws.com

      # Build da imagem Docker
      - name: Build the Docker image
        run: |
          docker build -t playlist .

      # Tag da imagem com o SHA do commit
      - name: Tag the Docker image
        run: |
          docker tag playlist:latest 024848472141.dkr.ecr.us-east-2.amazonaws.com/playlist:latest

      # Push da imagem para o ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 024848472141.dkr.ecr.us-east-2.amazonaws.com/playlist:latest
